# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/djbelyak/workspace/BinaryFileEditor

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/djbelyak/workspace/BinaryFileEditor

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/djbelyak/workspace/BinaryFileEditor/CMakeFiles /home/djbelyak/workspace/BinaryFileEditor/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/djbelyak/workspace/BinaryFileEditor/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named BinaryFileEditor

# Build rule for target.
BinaryFileEditor: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 BinaryFileEditor
.PHONY : BinaryFileEditor

# fast build rule for target.
BinaryFileEditor/fast:
	$(MAKE) -f CMakeFiles/BinaryFileEditor.dir/build.make CMakeFiles/BinaryFileEditor.dir/build
.PHONY : BinaryFileEditor/fast

FileReader.o: FileReader.cpp.o
.PHONY : FileReader.o

# target to build an object file
FileReader.cpp.o:
	$(MAKE) -f CMakeFiles/BinaryFileEditor.dir/build.make CMakeFiles/BinaryFileEditor.dir/FileReader.cpp.o
.PHONY : FileReader.cpp.o

FileReader.i: FileReader.cpp.i
.PHONY : FileReader.i

# target to preprocess a source file
FileReader.cpp.i:
	$(MAKE) -f CMakeFiles/BinaryFileEditor.dir/build.make CMakeFiles/BinaryFileEditor.dir/FileReader.cpp.i
.PHONY : FileReader.cpp.i

FileReader.s: FileReader.cpp.s
.PHONY : FileReader.s

# target to generate assembly for a file
FileReader.cpp.s:
	$(MAKE) -f CMakeFiles/BinaryFileEditor.dir/build.make CMakeFiles/BinaryFileEditor.dir/FileReader.cpp.s
.PHONY : FileReader.cpp.s

FileWriter.o: FileWriter.cpp.o
.PHONY : FileWriter.o

# target to build an object file
FileWriter.cpp.o:
	$(MAKE) -f CMakeFiles/BinaryFileEditor.dir/build.make CMakeFiles/BinaryFileEditor.dir/FileWriter.cpp.o
.PHONY : FileWriter.cpp.o

FileWriter.i: FileWriter.cpp.i
.PHONY : FileWriter.i

# target to preprocess a source file
FileWriter.cpp.i:
	$(MAKE) -f CMakeFiles/BinaryFileEditor.dir/build.make CMakeFiles/BinaryFileEditor.dir/FileWriter.cpp.i
.PHONY : FileWriter.cpp.i

FileWriter.s: FileWriter.cpp.s
.PHONY : FileWriter.s

# target to generate assembly for a file
FileWriter.cpp.s:
	$(MAKE) -f CMakeFiles/BinaryFileEditor.dir/build.make CMakeFiles/BinaryFileEditor.dir/FileWriter.cpp.s
.PHONY : FileWriter.cpp.s

Performer.o: Performer.cpp.o
.PHONY : Performer.o

# target to build an object file
Performer.cpp.o:
	$(MAKE) -f CMakeFiles/BinaryFileEditor.dir/build.make CMakeFiles/BinaryFileEditor.dir/Performer.cpp.o
.PHONY : Performer.cpp.o

Performer.i: Performer.cpp.i
.PHONY : Performer.i

# target to preprocess a source file
Performer.cpp.i:
	$(MAKE) -f CMakeFiles/BinaryFileEditor.dir/build.make CMakeFiles/BinaryFileEditor.dir/Performer.cpp.i
.PHONY : Performer.cpp.i

Performer.s: Performer.cpp.s
.PHONY : Performer.s

# target to generate assembly for a file
Performer.cpp.s:
	$(MAKE) -f CMakeFiles/BinaryFileEditor.dir/build.make CMakeFiles/BinaryFileEditor.dir/Performer.cpp.s
.PHONY : Performer.cpp.s

Previewer.o: Previewer.cpp.o
.PHONY : Previewer.o

# target to build an object file
Previewer.cpp.o:
	$(MAKE) -f CMakeFiles/BinaryFileEditor.dir/build.make CMakeFiles/BinaryFileEditor.dir/Previewer.cpp.o
.PHONY : Previewer.cpp.o

Previewer.i: Previewer.cpp.i
.PHONY : Previewer.i

# target to preprocess a source file
Previewer.cpp.i:
	$(MAKE) -f CMakeFiles/BinaryFileEditor.dir/build.make CMakeFiles/BinaryFileEditor.dir/Previewer.cpp.i
.PHONY : Previewer.cpp.i

Previewer.s: Previewer.cpp.s
.PHONY : Previewer.s

# target to generate assembly for a file
Previewer.cpp.s:
	$(MAKE) -f CMakeFiles/BinaryFileEditor.dir/build.make CMakeFiles/BinaryFileEditor.dir/Previewer.cpp.s
.PHONY : Previewer.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/BinaryFileEditor.dir/build.make CMakeFiles/BinaryFileEditor.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/BinaryFileEditor.dir/build.make CMakeFiles/BinaryFileEditor.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/BinaryFileEditor.dir/build.make CMakeFiles/BinaryFileEditor.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... BinaryFileEditor"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... FileReader.o"
	@echo "... FileReader.i"
	@echo "... FileReader.s"
	@echo "... FileWriter.o"
	@echo "... FileWriter.i"
	@echo "... FileWriter.s"
	@echo "... Performer.o"
	@echo "... Performer.i"
	@echo "... Performer.s"
	@echo "... Previewer.o"
	@echo "... Previewer.i"
	@echo "... Previewer.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

